apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-keda-scaler
  namespace: ai-task-platform
spec:
  scaleTargetRef:
    name: worker
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: task:queue
        listLength: "5"
        activationListLength: "1"
